# Generated by Django 5.0.6 on 2024-07-03 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registered_users',
            },
        ),
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('social_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_id', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.accounttypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users')),
            ],
            options={
                'unique_together': {('user', 'account_type')},
            },
        ),
    ]
